### ISSUE TITLE
Sólo deseo tener el código lo antes posible

### ISSUE THREAD

**Issue by percival45** [onuba/spring-jpa-hibernate-sample#1]
asistí a tu charla en el IES Cristobal de Monroy y estoy muy interesado en tener el código que allí expusiste,
Por cierto, me pareció muy buena tu exposición, ¡Sigue así!
 grácias

**Comment by onuba** [comment]
Hola!

Ya está el código subido, lo puedes descargar, hacer fork o lo que estimes conveniente :D.

Gracias!
